version: '2'
services:
  shipping:
     build: .
     hostname: shipping
     container_name: shipping
     image: connector/shipping
     restart: always
     networks:
       - public
     ports:
       - "2096:2096"
     volumes:
       - ./connector:/service/

networks:
  public:
    driver: bridge
