apiVersion: v1
kind: Service
metadata:
  name: connector-correspondence
spec:
  type: NodePort
  #clusterIP: 10.3.245.78
  ports:
    - port: 2094
      nodePort: 30050
  selector:
    name: connector-correspondence
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-correspondence
spec:
  replicas: 2
  template:
    metadata:
      name: connector-correspondence
      labels:
        name: connector-correspondence
        app: connector-correspondence
    spec:
      containers:
        - name: connector-correspondence
          image: asia.gcr.io/connectors-166702/connector-correspondence
          env:
            - name: OAUTH2_SERVER
              value: Server:Port
          ports:
            - containerPort: 2094