kind: Pod
apiVersion: v1
metadata:
  name: connector-correspondence
  labels:
    name: connector-correspondence
spec:
  containers:
    - name: connector-correspondence
      image: asia.gcr.io/connectors-166702/connector-correspondence
      ports:
        - containerPort: 2094
