apiVersion: v1
kind: Service
metadata:
  name: connector-catalogue
spec:
  type: NodePort
  #clusterIP: 10.3.248.155
  ports:
    - port: 2092
      nodePort: 30060
  selector:
    name: connector-catalogue
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-catalogue
spec:
  replicas: 2
  template:
    metadata:
      name: connector-catalogue
      labels:
        name: connector-catalogue
        app: connector-catalogue
    spec:
      containers:
        - name: connector-catalogue
          image: asia.gcr.io/connectors-166702/connector-catalogue
          env:
            - name: OAUTH2_SERVER
              value: Server:Port
          ports:
            - containerPort: 2092
