kind: Pod
apiVersion: v1
metadata:
  name: connector-catalogue
  labels:
    name: connector-catalogue
    app: connector-catalogue
spec:
  containers:
    - name: connector-catalogue
      image: asia.gcr.io/connectors-166702/connector-catalogue
      ports:
        - containerPort: 2092
