apiVersion: v1
kind: Service
metadata:
  name: connector-payment
spec:
  type: NodePort
  #clusterIP: 10.3.254.89
  ports:
    - port: 2090
      nodePort: 30040
  selector:
    name: connector-payment
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-payment
spec:
  replicas: 2
  template:
    metadata:
      name: connector-payment
      labels:
        name: connector-payment
        app: connector-payment
    spec:
      containers:
        - name: connector-payment
          image: asia.gcr.io/connectors-166702/connector-payment
          env:
            - name: OAUTH2_SERVER
              value: Server:Port
          ports:
            - containerPort: 2090