kind: Pod
apiVersion: v1
metadata:
  name: connector-oauth
  labels:
    name: connector-oauth
spec:
  containers:
    - name: connector-oauth
      image: asia.gcr.io/connectors-166702/connector-oauth
      ports:
        - containerPort: 2088
