apiVersion: v1
kind: Service
metadata:
  name: connector-loyalty
spec:
  type: NodePort
  #clusterIP: 10.0.0.54
  #clusterIP: 10.3.254.164
  ports:
    - port: 3000
      nodePort: 30090
  selector:
    name: connector-loyalty
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-loyalty
spec:
  replicas: 2
  template:
    metadata:
      name: connector-loyalty
      labels:
        name: connector-loyalty
        app: connector-loyalty
    spec:
      containers:
        - name: connector-loyalty
          image: asia.gcr.io/connectors-166702/connector-loyalty
          env:
            - name: OAUTH2_SERVER
              value: Server:Port
          ports:
            - containerPort: 3000