kind: Pod
apiVersion: v1
metadata:
  name: connector-loyalty
  labels:
    name: connector-loyalty
spec:
  containers:
    - name: connector-loyalty
      image: asia.gcr.io/connectors-166702/connector-loyalty
      ports:
        - containerPort: 3000
