apiVersion: v1
kind: Service
metadata:
  name: connector-service
spec:
  type: NodePort
  #clusterIP: 10.3.244.234
  ports:
    - port: 3002
      nodePort: 30032
      targetPort: 3002
      protocol: TCP
      name: http
  selector:
    name: connector-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-service
spec:
  replicas: 2
  template:
    metadata:
      name: connector-service
      labels:
        name: connector-service
        app: connector-service
    spec:
      containers:
        - name: connector-service
          image: asia.gcr.io/connectors-166702/connector-service
          ports:
            - containerPort: 3002