kind: Pod
apiVersion: v1
metadata:
  name: connector-service
  labels:
    name: connector-service
spec:
  containers:
    - name: connector-service
      image: asia.gcr.io/connectors-166702/connector-service
      ports:
        - containerPort: 3002
