version: '2'
services:
  catalogue:
     build: .
     hostname: catalogue
     container_name: catalogue
     image: connector/catalogue
     restart: always
     networks:
       - public
     ports:
       - "2092:2092"
     volumes:
       - ./connector:/service/

networks:
  public:
    driver: bridge
