apiVersion: v1
kind: Service
metadata:
  name: connector-tax
spec:
  type: NodePort
  #clusterIP: 10.3.246.65
  ports:
    - port: 2098
      nodePort: 30080
  selector:
    name: connector-tax
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-tax
spec:
  replicas: 2
  template:
    metadata:
      name: connector-tax
      labels:
        name: connector-tax
        app: connector-tax
    spec:
      containers:
        - name: connector-tax
          image: asia.gcr.io/connectors-166702/connector-tax
          env:
            - name: OAUTH2_SERVER
              value: Server:Port
          ports:
            - containerPort: 2098