FROM java:openjdk-8-jdk

#RUN apt-get update
#RUN apt-get install apt-utils -y
#RUN apt-get install telnet -y
#RUN apt-get update
#RUN apt-get install mysql-client -y

CMD ["/service/exec.sh", "start"]

