version: '2'
services:
  loyalty:
     build: .
     hostname: loyalty
     container_name: loyalty
     image: connector/loyalty
     restart: always
     networks:
       - public
     ports:
       - "3000:3000"
     volumes:
       - ./connector:/service/

networks:
  public:
    driver: bridge
