apiVersion: v1
kind: Service
metadata:
  name: connector-shipping
spec:
  type: NodePort
  #clusterIP: 10.3.248.12
  ports:
    - port: 2096
      nodePort: 30070
  selector:
    name: connector-shipping
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
 name: connector-shipping
spec:
  replicas: 2
  template:
    metadata:
      name: connector-shipping
      labels:
        name: connector-shipping
        app: connector-shipping
    spec:
      containers:
        - name: connector-shipping
          image: asia.gcr.io/connectors-166702/connector-shipping
          env:
            - name: OAUTH2_SERVER
              value: Server:Port
          ports:
            - containerPort: 2096